name: frappe_form
description: "A library to render Frappe DocForm and generate a response"
version: 0.0.1
repository: https://github.com/luis901101/frappe_form
issue_tracker: https://github.com/luis901101/frappe_form/issues
topics:
  - frappe
  - erpnext
  - form

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  html_editor_enhanced: ^2.6.0
  intl: '>=0.19.0 <1.0.0'
  intl_phone_field: ^3.2.0
  validators: ^3.0.0
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.1
  equatable: ^2.0.7

dependency_overrides:
  lints: ^5.1.1 # Necessary override because frappe_form depends on html_editor_enhanced which depends on lints < 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15 #flutter packages pub run build_runner build
  json_serializable: ^6.9.5
  copy_with_extension_gen: ^6.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
