class DocFormSamples {
  static String get sampleStructure => r'''
{
  "name": "SampleStructure",
  "creation": "2025-04-29 10:01:37.045763",
  "modified": "2025-05-06 14:54:06.879650",
  "modified_by": "user@mail.com",
  "owner": "user@mail.com",
  "docstatus": 0,
  "idx": 0,
  "issingle": 0,
  "is_virtual": 0,
  "is_tree": 0,
  "istable": 0,
  "editable_grid": 0,
  "track_changes": 0,
  "module": "Culinary Forms",
  "naming_rule": "",
  "sort_field": "modified",
  "sort_order": "DESC",
  "read_only": 0,
  "in_create": 0,
  "allow_copy": 0,
  "allow_rename": 1,
  "allow_import": 0,
  "hide_toolbar": 0,
  "track_seen": 0,
  "max_attachments": 0,
  "document_type": "",
  "engine": "InnoDB",
  "is_submittable": 0,
  "show_name_in_global_search": 0,
  "custom": 1,
  "beta": 0,
  "has_web_view": 0,
  "allow_guest_to_view": 0,
  "email_append_to": 0,
  "show_title_field_in_link": 0,
  "translated_doctype": 0,
  "is_calendar_and_gantt": 0,
  "quick_entry": 0,
  "track_views": 0,
  "queue_in_background": 0,
  "allow_events_in_timeline": 0,
  "allow_auto_repeat": 0,
  "make_attachments_public": 0,
  "force_re_route_to_default_view": 0,
  "show_preview_popup": 0,
  "index_web_pages_for_search": 1,
  "doctype": "DocType",
  "actions": [],
  "states": [],
  "fields": [
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflce7r67",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Tab Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 1,
      "__run_link_triggers": 1,
      "fieldname": "tab_1",
      "label": "Tab 1",
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl55d3u2",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Section Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 2,
      "fieldname": "section_inputs",
      "label": "Section Inputs",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl94v2t5",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Column Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 3,
      "fieldname": "column_break_pnys",
      "label": "",
      "show_preview_popup": 0,
      "columns": 0,
      "description": "",
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl17p7m7",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Heading",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 4,
      "fieldname": "this_is_a_heading",
      "label": "This is a heading ",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl4hbpam",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Data",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 1,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 1,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 5,
      "fieldname": "data",
      "label": "Data",
      "show_preview_popup": 0,
      "columns": 0,
      "description": "Write something short like a name",
      "length": 160,
      "documentation_url": "",
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflblga3d",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Phone",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 6,
      "fieldname": "phone",
      "label": "Phone",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflq6tvvp",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Autocomplete",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 1,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 7,
      "fieldname": "autocomplete",
      "label": "Autocomplete",
      "options": "One\nTwo\nThree",
      "show_preview_popup": 0,
      "columns": 0,
      "default": "",
      "description": "Write something to autocomplete, like One, Two or Three",
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflrj0j07",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Password",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 8,
      "fieldname": "password",
      "label": "Password",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflsd522c",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Select",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 1,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 9,
      "fieldname": "select",
      "label": "Select",
      "options": "Select 1\nSelect 2\nSelect 3",
      "show_preview_popup": 0,
      "columns": 0,
      "default": "Select 2",
      "description": "Dropdown with default value = Select 2. If you choose Select 1, the Percent field will show up.",
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflc6iq70",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Percent",
      "precision": "2",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 10,
      "fieldname": "percent",
      "label": "Percent",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "default": "",
      "depends_on": "eval:doc.select=='Select 1'",
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflv3nqmv",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Currency",
      "precision": "4",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 11,
      "fieldname": "currency",
      "label": "Currency",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflcrvp5n",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Float",
      "precision": "5",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 12,
      "fieldname": "float",
      "label": "Float",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflif8mrq",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Int",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 13,
      "fieldname": "integer",
      "label": "Integer",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl59de3m",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Rating",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 14,
      "fieldname": "rating",
      "label": "Rating",
      "show_preview_popup": 0,
      "columns": 0,
      "default": "",
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflfr8r57",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Column Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 15,
      "fieldname": "column_break_bpxe",
      "label": "",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflf5gj4d",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Text Editor",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 16,
      "fieldname": "text_editor",
      "label": "Text Editor",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfltvv03p",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Text",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 17,
      "fieldname": "text",
      "label": "Text",
      "show_preview_popup": 0,
      "columns": 0,
      "description": "",
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl56sks6",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Small Text",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 18,
      "fieldname": "small_text",
      "label": "Small Text",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl3nf0hr",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Long Text",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 19,
      "fieldname": "long_text",
      "label": "Long Text",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflvi9jeu",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Section Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 20,
      "fieldname": "section_date_time_duration",
      "label": "Date, Time and Duration",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl8l3ebi",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Date",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 21,
      "fieldname": "date",
      "label": "Date",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflhcdi1i",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Time",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 22,
      "fieldname": "time",
      "label": "Time",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflha8760",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Column Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 23,
      "__run_link_triggers": 1,
      "fieldname": "column_break_iwrx",
      "label": "",
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflnpb709",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Date",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 24,
      "__run_link_triggers": 1,
      "fieldname": "date1",
      "label": "Date1",
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl15tmb3",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Time",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 25,
      "__run_link_triggers": 1,
      "fieldname": "time1",
      "label": "Time1",
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflct355c",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Column Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 26,
      "__run_link_triggers": 1,
      "fieldname": "column_break_azix",
      "label": "",
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflprfern",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Date",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 27,
      "__run_link_triggers": 1,
      "fieldname": "date2",
      "label": "Date2",
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflcm8o8u",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Time",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 28,
      "__run_link_triggers": 1,
      "fieldname": "time2",
      "label": "Time2",
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflli76hp",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Column Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 29,
      "fieldname": "column_break_zomy",
      "label": "",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflsviue0",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Datetime",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 30,
      "fieldname": "date_and_time",
      "label": "Date and Time",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflkrbl53",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Duration",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 31,
      "fieldname": "duration",
      "label": "Duration",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl92jko8",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Tab Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 32,
      "__run_link_triggers": 1,
      "fieldname": "tab_2",
      "label": "Tab 2",
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl11jpo5",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Section Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 33,
      "fieldname": "section_location",
      "label": "Location",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflsu0mgl",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Geolocation",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 34,
      "fieldname": "geolocation",
      "label": "Geolocation",
      "show_preview_popup": 0,
      "columns": 0,
      "default": "{\n  \"type\": \"FeatureCollection\",\n  \"features\": [\n    {\n      \"type\": \"Feature\",\n      \"properties\": {},\n      \"geometry\": { \"type\": \"Point\", \"coordinates\": [-9.208334, 38.757599] }\n    }\n  ]\n}",
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icfl64itkq",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Section Break",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 35,
      "fieldname": "section_attachments",
      "label": "Attachments",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflebfn4f",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Attach",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 36,
      "fieldname": "attach",
      "label": "Attach",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    },
    {
      "docstatus": 0,
      "doctype": "DocField",
      "name": "icflmkb9vd",
      "__unsaved": 1,
      "owner": "user@mail.com",
      "fieldtype": "Attach Image",
      "precision": "",
      "non_negative": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "reqd": 0,
      "is_virtual": 0,
      "search_index": 0,
      "sort_options": 0,
      "show_dashboard": 0,
      "fetch_if_empty": 0,
      "hidden": 0,
      "bold": 0,
      "allow_in_quick_entry": 0,
      "translatable": 0,
      "print_hide": 0,
      "print_hide_if_no_value": 0,
      "report_hide": 0,
      "collapsible": 0,
      "hide_border": 0,
      "in_list_view": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "in_filter": 0,
      "in_global_search": 0,
      "read_only": 0,
      "allow_on_submit": 0,
      "ignore_user_permissions": 0,
      "allow_bulk_edit": 0,
      "permlevel": 0,
      "ignore_xss_filter": 0,
      "unique": 0,
      "no_copy": 0,
      "set_only_once": 0,
      "remember_last_selected_value": 0,
      "parent": "SampleStructure",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 37,
      "fieldname": "attach_image",
      "label": "Attach Image",
      "show_preview_popup": 0,
      "columns": 0,
      "length": 0,
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com"
    }
  ],
  "permissions": [
    {
      "name": "kera1ibre6",
      "creation": "2025-04-29 10:01:37.045763",
      "modified": "2025-05-06 14:54:06.879650",
      "modified_by": "user@mail.com",
      "owner": "user@mail.com",
      "docstatus": 0,
      "parent": "SampleStructure",
      "parentfield": "permissions",
      "parenttype": "DocType",
      "idx": 1,
      "permlevel": 0,
      "role": "System Manager",
      "read": 1,
      "write": 1,
      "create": 1,
      "submit": 0,
      "cancel": 0,
      "delete": 1,
      "amend": 0,
      "report": 1,
      "export": 1,
      "import": 0,
      "share": 1,
      "print": 1,
      "email": 1,
      "if_owner": 0,
      "select": 0,
      "doctype": "DocPerm"
    }
  ],
  "links": [],
  "__unsaved": 0
}
  ''';

  static const tasteTester = r'''
{
  "name": "Taste Tester",
  "creation": "2025-04-21 15:33:05.551273",
  "modified": "2025-04-21 15:59:32.020543",
  "modified_by": "Administrator",
  "owner": "Administrator",
  "docstatus": 0,
  "idx": 0,
  "issingle": 0,
  "is_virtual": 0,
  "is_tree": 0,
  "istable": 0,
  "editable_grid": 0,
  "track_changes": 0,
  "module": "Culinary Forms",
  "sort_field": "modified",
  "sort_order": "DESC",
  "read_only": 0,
  "in_create": 0,
  "allow_copy": 0,
  "allow_rename": 1,
  "allow_import": 0,
  "hide_toolbar": 0,
  "track_seen": 0,
  "max_attachments": 0,
  "engine": "InnoDB",
  "is_submittable": 0,
  "show_name_in_global_search": 0,
  "custom": 0,
  "beta": 0,
  "has_web_view": 0,
  "allow_guest_to_view": 0,
  "email_append_to": 0,
  "show_title_field_in_link": 0,
  "migration_hash": "03072412bad356903a667dcda7c5798c",
  "translated_doctype": 0,
  "is_calendar_and_gantt": 0,
  "quick_entry": 0,
  "track_views": 0,
  "queue_in_background": 0,
  "allow_events_in_timeline": 0,
  "allow_auto_repeat": 0,
  "make_attachments_public": 0,
  "force_re_route_to_default_view": 0,
  "show_preview_popup": 0,
  "index_web_pages_for_search": 1,
  "doctype": "DocType",
  "actions": [],
  "states": [],
  "fields": [
    {
      "name": "vto3h3uncq",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 1,
      "fieldname": "product",
      "label": "Product",
      "fieldtype": "Data",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 1,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto316mrc5",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 2,
      "fieldname": "project",
      "label": "Project",
      "fieldtype": "Autocomplete",
      "options": "CWB\nLKK\nCDF\nOther",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 1,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 1,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3pu0535",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 3,
      "fieldname": "other_project",
      "label": "Other Project",
      "fieldtype": "Small Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "depends_on": "eval: doc.project == \"Other\"",
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto38iaf6j",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 4,
      "fieldname": "price_paid",
      "label": "Price Paid",
      "fieldtype": "Float",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "precision": "2",
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto32q14kb",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 5,
      "fieldname": "column_break_fqyb",
      "fieldtype": "Column Break",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto35pnotk",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 6,
      "fieldname": "purchased_at",
      "label": "Purchased at",
      "fieldtype": "Select",
      "options": "Write Text\nSelect Location",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "default": "Write Text",
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto31d40ue",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 7,
      "fieldname": "purchased_at_write_a_description",
      "label": "Purchased at (Write a description)",
      "fieldtype": "Long Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "depends_on": "eval: doc.purchased_at == \"Write Text\"",
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto31thh0q",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 8,
      "fieldname": "purchased_at_location",
      "label": "Select Location",
      "fieldtype": "Geolocation",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "depends_on": "eval: doc.purchased_at == \"Select Location\"",
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3svgvmv",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 9,
      "fieldname": "packaging_section",
      "label": "Packaging",
      "fieldtype": "Section Break",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3n333ht",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 10,
      "fieldname": "photo_packaging",
      "label": "Take Photos of Packaging",
      "fieldtype": "Attach Image",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3oniggf",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 11,
      "fieldname": "packaging_notes",
      "label": "Packagin Notes",
      "fieldtype": "Long Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3s6tivu",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 12,
      "fieldname": "column_break_guml",
      "fieldtype": "Column Break",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto32nhrkd",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 13,
      "fieldname": "ingredients",
      "label": "Ingredients",
      "fieldtype": "Long Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto35m8ne8",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 14,
      "fieldname": "flavour_evaluation_section",
      "label": "Flavour Evaluation",
      "fieldtype": "Section Break",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3d4097k",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 15,
      "fieldname": "appearence",
      "label": "Appearence",
      "fieldtype": "Long Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3lvbeva",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 16,
      "fieldname": "texture",
      "label": "Texture",
      "fieldtype": "Long Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto322eqoc",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 17,
      "fieldname": "total_flavor_experience",
      "label": "Total Flavor Experience",
      "fieldtype": "Long Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3gp0q7i",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 18,
      "fieldname": "column_break_hdfx",
      "fieldtype": "Column Break",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3fku2u9",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 19,
      "fieldname": "aroma",
      "label": "Aroma",
      "fieldtype": "Long Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3oup956",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 20,
      "fieldname": "taste",
      "label": "Taste",
      "fieldtype": "Table",
      "options": "Flavour Evaluation Taste",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto30bs9pd",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 21,
      "fieldname": "after_taste",
      "label": "After Taste",
      "fieldtype": "Long Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto394siok",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 22,
      "fieldname": "section_break_mcld",
      "fieldtype": "Section Break",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto39esb9k",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 23,
      "fieldname": "marketpalce_analysis",
      "label": "Marketpalce Analysis",
      "fieldtype": "Long Text",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "description": "Would you buy it? If so why or why not? What would you change?",
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3h2fh6e",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 24,
      "fieldname": "video_review",
      "label": "Video Review",
      "fieldtype": "Attach",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    },
    {
      "name": "vto3l2cea8",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "fields",
      "parenttype": "DocType",
      "idx": 25,
      "fieldname": "final_rating",
      "label": "Final Rating",
      "fieldtype": "Rating",
      "search_index": 0,
      "show_dashboard": 0,
      "hidden": 0,
      "set_only_once": 0,
      "allow_in_quick_entry": 0,
      "print_hide": 0,
      "report_hide": 0,
      "reqd": 0,
      "bold": 0,
      "in_global_search": 0,
      "collapsible": 0,
      "unique": 0,
      "no_copy": 0,
      "allow_on_submit": 0,
      "show_preview_popup": 0,
      "permlevel": 0,
      "ignore_user_permissions": 0,
      "columns": 0,
      "in_list_view": 0,
      "fetch_if_empty": 0,
      "in_filter": 0,
      "remember_last_selected_value": 0,
      "ignore_xss_filter": 0,
      "print_hide_if_no_value": 0,
      "allow_bulk_edit": 0,
      "in_standard_filter": 0,
      "in_preview": 0,
      "read_only": 0,
      "length": 0,
      "translatable": 0,
      "hide_border": 0,
      "hide_days": 0,
      "hide_seconds": 0,
      "non_negative": 0,
      "is_virtual": 0,
      "sort_options": 0,
      "doctype": "DocField"
    }
  ],
  "permissions": [
    {
      "name": "vto3otsj1m",
      "creation": "2025-04-21 15:33:05.551273",
      "modified": "2025-04-21 08:34:24.339479",
      "modified_by": "Administrator",
      "owner": "Administrator",
      "docstatus": 0,
      "parent": "Taste Tester",
      "parentfield": "permissions",
      "parenttype": "DocType",
      "idx": 1,
      "permlevel": 0,
      "role": "System Manager",
      "read": 1,
      "write": 1,
      "create": 1,
      "submit": 0,
      "cancel": 0,
      "delete": 1,
      "amend": 0,
      "report": 1,
      "export": 1,
      "import": 0,
      "share": 1,
      "print": 1,
      "email": 1,
      "if_owner": 0,
      "select": 0,
      "doctype": "DocPerm"
    }
  ],
  "links": []
}  
  ''';
}
